name: Auto Bump Version

on:
  workflow_call:
    inputs:
      branch:
        default: 'master'
        required: false
        type: string
      semver:
        default: 'patch'
        required: false
        type: string
      package_path:
        required: false
        type: string
        default: './'
      node-version:
        required: false
        type: string
        default: "22"
    secrets:
      github-token:
        required: true

permissions:
  contents: write

jobs:
  auto-bump:
    name: Auto Bump ${{ inputs.semver }} on ${{ inputs.branch }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.github-token }}
          ref: ${{ inputs.branch }}

      - name: Skip if last commit was an auto-bump
        id: skip-check
        run: |
          msg=$(git log -1 --pretty=%B HEAD)
          echo "Last commit message: $msg"
          if [[ "$msg" == chore\(package\):\ auto\ bump\ version\ to* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        if: steps.skip-check.outputs.skip == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Bump ${{ inputs.semver }} version
        if: steps.skip-check.outputs.skip == 'false'
        id: bump
        working-directory: ${{ inputs.package_path }}
        run: |
          current_version=$(jq -r '.version' package.json)
          echo "Current version: $current_version"

          IFS='.' read -r major minor patch <<< "$current_version"
          case "${{ inputs.semver }}" in
            patch) patch=$((patch + 1));;
            minor) minor=$((minor + 1)); patch=0;;
            major) major=$((major + 1)); minor=0; patch=0;;
            *) echo "Invalid semver input"; exit 1;;
          esac

          new_version="$major.$minor.$patch"
          echo "New version: $new_version"

          jq ".version = \"$new_version\"" package.json > package.tmp.json && mv package.tmp.json package.json
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        if: steps.skip-check.outputs.skip == 'false'
        working-directory: ${{ inputs.package_path }}
        run: |
          git config user.email "deploy-bot@riverigaming.com"
          git config user.name "rig-autobot[version-bump]"
          git add package.json
          git commit -m "chore(package): auto bump version to ${{ steps.bump.outputs.new_version }}"
          git push origin ${{ inputs.branch }}

      - name: Set output if version was bumped
        id: set_output
        run: |
          if [[ $(git diff --name-only HEAD~1..HEAD) == *"package.json"* ]]; then
            echo "version_bumped=true" >> $GITHUB_ENV
          else
            echo "version_bumped=false" >> $GITHUB_ENV
          fi

    outputs:
      version_bumped: ${{ env.version_bumped }}
