name: Check Node package.json Version Bump
on:
  workflow_call:
    inputs:
      fail-on-match:
        description: Fail if the version in the pull request is the same as the base branch
        required: true
        type: boolean
        default: true
jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    outputs:
      isVersionMatch: ${{ steps.check-version.outputs.match }}

    steps:
      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          sparse-checkout: package.json
          sparse-checkout-cone-mode: false

      - name: Get the current version
        id: current
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Checkout base branch code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          sparse-checkout: package.json
          sparse-checkout-cone-mode: false

      - name: Get the base branch version
        id: base
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Check version bump
        id: check-version
        run: |
          current_version="${{ steps.current.outputs.version }}"
          base_version="${{ steps.base.outputs.version }}"

          if [[ "$(printf '%s\n' "$current_version" "$base_version" | sort -V | tail -n 1)" == "$base_version" ]]; then
            echo "package.json version is not greater than the base branch. Please bump the version."
            echo "::set-output match=true"
            if ${{ inputs.fail-on-match == true }}; then
              exit 1
            fi
          else
            echo "package.json version has been bumped in the pull request."
            echo "::set-output match=false"
          fi