name: .NET Build and Publish

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: dotnet version to use (defaults to 7.0.x)
        required: false
        type: string
        default: "7.0.x"
      dotnet-publish-version:
        description: dotnet version to use for publish (defaults to net7.0)
        required: false
        type: string
        default: net7.0
      service-name:
        description: service-name to build in docker.compose file
        required: false
        type: string
        default: build
      solution:
        description: path to project solution
        required: true
        type: string
      publish:
        description: whether the docker image should be pushed
        required: false
        type: boolean
        default: false
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      PUBLISH_PATH: specs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environmental variables
        run: |
          echo "SOLUTION=${{ inputs.solution }}" >> $GITHUB_ENV
          echo "APP_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Generate Version Number
        id: version-builder
        uses: River-iGaming/actions/dotnet/versions@v2
        with:
          type: dotnet-app
          package-version: ${{ env.PACKAGE_VERSION }}

      - name: Check if Git Tag exists
        env:
          APP_VERSION: ${{ steps.version-builder.outputs.version }}
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/$APP_VERSION$"; then
              echo "::error::tag $APP_VERSION already exists."
              exit 1
          fi
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - uses: actions/cache@v4
        name: Setup Cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/package.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore $SOLUTION /p:Configuration=Release

      - name: Publish
        run: dotnet publish $SOLUTION -f ${{ inputs.dotnet-publish-version }} -c Release -o ./$PUBLISH_PATH --no-restore

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Docker buildx
        id: buildx-setup
        uses: docker/setup-buildx-action@v2

      - name: Build, tag, and push image to Amazon ECR
        if: ${{ inputs.publish }}
        env:
          ECR_HOST: ${{ steps.login-ecr.outputs.registry }}
          GIT_COMMIT: ${{ github.sha }}
        run: |
          docker buildx bake -f docker-compose.yml ${{inputs.service-name}} --progress plain --push

      - name: Create git tag for release
        env:
          VERSION: ${{ steps.version-builder.outputs.version }}
        run: |
          git tag $VERSION
          git push origin $VERSION
          echo "::notice::Pushed image for $APP_NAME: $VERSION"
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
