name: Downmerge releases

on:
  workflow_call:
    inputs:
        base-branch:
          description: Base branch of the repo to downmerge to
          required: false
          type: string
          default: "master"
    secrets:
      github-token:
        required: true

jobs:
  check-allowed:
    name: Downmerge to a base and release branches
    runs-on: ubuntu-latest
    steps:
      - name: Check if Downmerge Allowed
        id: check-commit-type
        uses: River-iGaming/actions/commit-type-check@feature/commit-type-check
        with:
          commit-types: |
            feat
            fix
            release
          github-token: ${{ secrets.github-token }}

      - name: Downmerge is not allowed
        if: ${{ steps.check-commit-type.outputs.allowed == 'false' }}
        run: |
          echo "::error::Downmerge is not allowed for this commit type."
          exit 1

  get-branches:
    name: Get Branches for Downmerge
    needs: check-allowed
    runs-on: ubuntu-latest
    outputs:
      downmerge-branches: ${{ steps.get-branches.outputs.downmerge-branches }}
      current-branch: ${{ steps.get-branches.outputs.current-branch }}
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.github-token }}
      
      - name: Get Branches
        id: get-branches
        run: |
          git fetch
          git config user.email "deploy-bot@riverigaming.com"
          git config user.name "rig-autobot"

          # Determine the current branch and package version
          BASE_BRANCH="${{ inputs.base-branch }}"
          CURRENT_BRANCH="$(git branch --show-current)"

          if [[ "$CURRENT_BRANCH" =~ "release" ]]; then
            BASE_PACKAGE_VERSION=$(echo $CURRENT_BRANCH | cut -d'/' -f2)
          else
            BASE_PACKAGE_VERSION=$(jq -r '.version' package.json)
          fi

          # Get a list of branches for downmerge
          BRANCHES=$(git for-each-ref --format='%(refname:short)' 'refs/remotes/origin/release-test/*' "refs/remotes/origin/$BASE_BRANCH")
          DOWNMERGE_BRANCHES=()
          for branch in $BRANCHES; do
            branch="${branch#origin/}" # Remove the 'origin/' prefix
            BRANCH_VERSION=$(echo $branch | cut -d'/' -f2)
            NEWER_VERSION="$(printf '%s\n' "$BRANCH_VERSION" "$BASE_PACKAGE_VERSION" | sort -V | tail -n 1)"

            if [[ $branch == $BASE_BRANCH || ($NEWER_VERSION == $BRANCH_VERSION && "$BRANCH_VERSION" != "$BASE_PACKAGE_VERSION") ]]; then
              DOWNMERGE_BRANCHES+=("$branch")
            fi
          done

          echo "::notice::Branches to merge: ${DOWNMERGE_BRANCHES[*]}"

          BRANCHES=$(printf '%s\n' "${DOWNMERGE_BRANCHES[@]}" | jq -R . | jq -cs .)
          echo "downmerge-branches=$(IFS=', '; echo "${BRANCHES[*]}")" >> "$GITHUB_OUTPUT"
          echo "current-branch=$CURRENT_BRANCH" >> $GITHUB_OUTPUT
  downmerge:
    name: Downmerge to ${{ matrix.branch }}
    needs: get-branches
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.get-branches.outputs.downmerge-branches) }}
    steps:
      - name: Merge ${{ needs.get-branches.outputs.current-branch }} to ${{ matrix.branch }}
        id: downmerge
        uses: River-iGaming/actions/merge@feature/merge-branch
        with:
          source-branch: ${{ needs.get-branches.outputs.current-branch }}
          target-branch: ${{ matrix.branch }}
          version-files: |
            package.json
            pnpm-lock.yaml
          github-token: ${{ secrets.github-token }}
