name: Downmerge releases

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  checks:
    name: Downmerge to develop and release branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.github-token }}

      - name: Downmerge
        run: |
          git fetch
          git config user.email "deploy-bot@riverigaming.com"
          git config user.name "rig-autobot"

          # Determine the current package version
          BASE_PACKAGE_VERSION=$(node -p "require('./package.json').version")

          # Extract the major and minor version from the current version
          MAJOR_VERSION=$(echo $BASE_PACKAGE_VERSION | cut -d'.' -f1)
          MINOR_VERSION=$(echo $BASE_PACKAGE_VERSION | cut -d'.' -f2)

          CURRENT_BRANCH="$(git branch --show-current)"

          # Iterate through branches and downmerge if they match the pattern
          for branch in $(git for-each-ref --format='%(refname:short)' 'refs/remotes/origin/release/*' 'refs/remotes/origin/develop'); do
            BRANCH_VERSION=$(echo $branch | cut -d'/' -f2)
            MAJOR_MINOR_BRANCH_VERSION=$(echo $BRANCH_VERSION | cut -d'.' -f1,2)
            MAJOR_MINOR_PACKAGE_VERSION=$(echo $BASE_PACKAGE_VERSION | cut -d'.' -f1,2)

            echo "::notice ::Downmerging check branch: $branch from: $CURRENT_BRANCH"
            echo "::notice ::branch version: $BRANCH_VERSION"
            echo "::notice ::Major minor branch version: $MAJOR_MINOR_BRANCH_VERSION"
            echo "::notice ::Major minor Package version: $MAJOR_MINOR_PACKAGE_VERSION"

            if [[ $branch == "develop" || $MAJOR_MINOR_BRANCH_VERSION > $MAJOR_MINOR_PACKAGE_VERSION ]]; then
              echo "::notice ::Downmerging branch: $branch from: $CURRENT_BRANCH"

              git checkout $branch

              # Merge changes from the remote branch into branch
              if git merge --no-commit --no-ff --no-edit ${CURRENT_BRANCH}; then
                if [ -z "$(git status --porcelain)" ]; then
                  echo "::notice ::Nothing to commit for branch: $branch"
                else
                  git commit --no-edit
                  git push origin $branch
                fi
              else
                if git merge --abort; then
                  CONFLICTS="$(git diff --name-only --diff-filter=U)"

                  for file in $CONFLICTS; do
                    if [ "$file" == "package.json" ]; then
                      # Parse the package.json file to check version conflicts
                      BASE_VERSION=$(jq -r .version ${CURRENT_BRANCH}/package.json)
                      HEAD_VERSION=$(jq -r .version $branch/package.json)

                      if [ "$BASE_VERSION" != "$HEAD_VERSION" ]; then
                        # Auto-resolve the conflict by choosing the HEAD version
                        echo "Auto-resolving package.json version conflict by choosing the HEAD version."
                        git checkout --theirs package.json
                        git add package.json
                        git commit -m "Auto-resolve package.json version conflict"
                        git push origin $branch
                      else
                        echo "Conflict in package.json, but version numbers are the same."
                      fi
                    else
                      echo "::warning ::Failed to downmerge to branch: $branch. Merge error."
                    fi
                  done
                fi
              fi
            fi
          done
