name: Frontend Build and Publish Library
on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use (defaults to 14)
        required: false
        type: string
        default: '14'
      junit-report-path:
        description: The path to unit test report (defaults to ./junit/)
        required: false
        type: string
        default: ./junit/
      junit-report-name:
        description: The file name for unit test report (defaults to test-results.xml)
        required: false
        type: string
        default: test-results.xml
      aws-region:
        description: Which AWS region to use for publish storybook (defaults to eu-west-1)
        required: false
        type: string
        default: eu-west-1
    secrets:
      npm-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  build:
    name: Build and publish library
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          always-auth: true
          registry-url: https://www.myget.org/F/river-tech/npm/
          scope: '@odin'

      - name: Print environment versions
        run: |
          NODE_V=$(node --version)
          NPM_V=$(npm -v)
          echo node version':' $NODE_V
          echo npm version':' $NPM_V

      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Install npm
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test -- --browsers=ChromeHeadlessCI --no-watch --no-progress

      - name: Build storybook
        run: npm run build:storybook

      - name: Check if commit is publishable
        id: commit
        run: |
          if git log --format=%B -n 1 | egrep "^(style|test|docs)"; then
            echo "::set-output name=publishable::false"
            echo "This update doesn't need to be published; finishing build..."
          else 
            echo "::set-output name=publishable::true"
          fi

      - name: Fetch git tags
        if: ${{ steps.commit.outputs.publishable == 'true' }}
        run: |
          git fetch --prune --unshallow --tags

      - name: Check if tag exists
        id: tag
        if: ${{ steps.commit.outputs.publishable == 'true' }}
        run: |
          TAG=$(node -p "require('./lerna.json').version")
          if git tag --list | grep "^$TAG$"; then
            echo "::set-output name=publishable::false"
            echo "Tag already exists. Please make sure you bump version!"
          else
            echo "::set-output name=publishable::true"
          fi

      - name: Configure AWS credentials
        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.publishable == 'true' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.publishable == 'true' }}
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish storybook
        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.publishable == 'true' }}
        env:
          ECR_HOST: ${{ steps.login-ecr.outputs.registry }} 
        run: |
          TAG=$(node -p "require('./storybook/package.json').version")
          if $GITHUB_REF_NAME == 'develop'
          then
            TAG=$TAG-dev-$GITHUB_RUN_ID
          elif [[ $GITHUB_REF_NAME =~ ^feature\/(.*)$ ]]
          then
            TAG=$TAG-demo-${BASH_REMATCH[1]}-$GITHUB_RUN_ID
          fi

          [[ $ECR_HOST =~ ^([0-9]*) ]] && REGISTRY=${BASH_REMATCH[1]}

          if aws ecr describe-images --repository-name=odin.ngx-storybook --registry-id $REGISTRY --image-ids=imageTag=$TAG > /dev/null 2>&1; then
            echo "$TAG already exists on remote... skipping..."
            exit 0
          fi

          npm run build:storybook

          TAG=$TAG docker-compose build
          TAG=$TAG docker-compose push

          if ! ([ $GITHUB_REF_NAME = "master" ] || [[ $GITHUB_REF_NAME =~ ^([0-9].*)\.x$ ]]); then
            echo "PUBLISHABLE=false" >> $GITHUB_ENV
            echo "Non-publishable branch; finishing build..."
          fi

      - name: Logout of Amazon ECR
        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.publishable == 'true' }}
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

      - name: Deploy
        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.publishable == 'true' }}
        run: |
          echo "git tag"
          PACKAGE_VERSION=$(node -p "require('./lerna.json').version")
          git tag $PACKAGE_VERSION
          git push --tags
          npm run publish:rel

      - name: Store tests artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ env.junit-report-name }}
          path: ${{ env.junit-report-path }}
          retention-days: 2

      - name: Store npm artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs/*
          retention-days: 2

