name: Comment on Core Files changed
on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  core-files-modified:
    name: Core Files Modified
    runs-on: ubuntu-latest
    steps:
      - name: Check changed files
        uses: actions/checkout@v3

      - name: Get modified core files excluding the app files
        id: modified-files-excluded
        uses: tj-actions/changed-files@v35
        with:
          files_ignore_separator: ","
          dir_names: true
          files: "ClientApp/src/**/*.{ts,html,scss}"
          files_ignore: "*.app.*, *.vars.*, index.*"
          separator: ", "

      - name: Print modified core files
        run: echo "${{ steps.modified-files-excluded.outputs.all_changed_files }}"

      - name: Comment If Core Files Change
        if: steps.modified-files-excluded.outputs.any_changed == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Core files have been modified make sure QA are aware of changes in: ${{ steps.modified-files-excluded.outputs.all_changed_files }}
          comment_tag: modifier-core
          mode: recreate