name: Frontend Build and Tag Configs
on:
  workflow_call:
    inputs:
      aws-region:
        description: Which AWS region to use for publish storybook (defaults to eu-west-1)
        required: false
        type: string
        default: eu-west-1
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Print environment versions
        uses: mosteo-actions/docker-run@v1
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/deploy-ci:7.3.40
          command: ci deps

      - name: Lint JSON
        uses: mosteo-actions/docker-run@v1
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/deploy-ci:7.3.40
          command: ci lint-json "./config/**/*.json"

      - name: Logout of Amazon ECR
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

  tag:
    name: Tag
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Extract branch name
        id: branch
        run: |
          EVENT=${{ github.event_name }}
          if [ $EVENT == "pull_request" ]; then
            BRANCH_NAME=${{github.head_ref}}
            echo "::set-output name=name::${BRANCH_NAME}"
          else
            echo "::set-output name=name::${GITHUB_REF_NAME}"
          fi

      - name: Check if branch is publishable
        id: check-branch
        run: |
          BRANCH_NAME=${{steps.branch.outputs.name}}
          if ! ([[ $BRANCH_NAME =~ ^([0-9].*)\.x$ ]]); then
            echo "::set-output name=publishable::false"
            echo "::notice ::Non-publishable branch."
          else 
            echo "::set-output name=publishable::true"
          fi

      - name: Extract package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: tag
        with:
          tag: ${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Inform if tag exists
        if: ${{ steps.tag.outputs.exists == 'true' }}
        run: |
          echo "::error ::Tag already exists."
          exit 1

      - name: Git Tag
        if: ${{ steps.check-branch.outputs.publishable == 'true' }}
        run: |
          git tag $PACKAGE_VERSION
          git push origin $PACKAGE_VERSION
