name: Frontend Build and Publish Library
on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use (defaults to 14)
        required: false
        type: string
        default: '14'
      npm-registry-url:
        description: The url address for npm registry (defaults to https://www.myget.org/F/river-tech/npm/)
        required: false
        type: string
        default: https://www.myget.org/F/river-tech/npm/
      npm-registry-scope:
        description: The name of the npm scope (defaults to @odin)
        required: false
        type: string
        default: '@odin'
      junit-report-path:
        description: The path to unit test report (defaults to ./junit/)
        required: false
        type: string
        default: ./junit/
      junit-report-name:
        description: The file name for unit test report (defaults to test-results.xml)
        required: false
        type: string
        default: test-results.xml
    secrets:
      npm-token:
        required: true
      github-token:
        required: true
jobs:
  build:
    name: Build and publish library
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          always-auth: true
          registry-url: ${{ inputs.npm-registry-url }}
          scope: ${{ inputs.npm-registry-scope }}

      - name: Print environment versions
        run: |
          NODE_V=$(node --version)
          NPM_V=$(npm -v)
          echo node version':' $NODE_V
          echo npm version':' $NPM_V

      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Install npm
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test -- --browsers=ChromeHeadlessCI --no-watch --no-progress

      - name: Check if commit is publishable
        id: commit
        run: |
          if git log --format=%B -n 1 | egrep "^(style|test|docs)"; then
            echo "::set-output name=publishable::false"
            echo "::notice ::This update doesn't need to be published."
          else 
            echo "::set-output name=publishable::true"
          fi

      - name: Fetch tag from lerna
        id: lerna
        if: ${{ steps.commit.outputs.publishable == 'true' }}
        run: |
          TAG=$(node -p "require('./lerna.json').version")
          echo "::set-output name=tag::${TAG}"

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: tag
        with: 
          tag: ${{ steps.lerna.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Inform if tag exists
        if: ${{ steps.tag.outputs.exists == 'true' }}
        run: echo "::notice ::Tag already exists. Please make sure you bump version!"

      - name: Deploy
        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.exists == 'false' }}
        run: |
          echo "git tag"
          PACKAGE_VERSION=$(node -p "require('./lerna.json').version")
          git tag $PACKAGE_VERSION
          git push --tags
          npm run publish:rel

      - name: Store tests artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ inputs.junit-report-name }}
          path: ${{ inputs.junit-report-path }}
          retention-days: 2

      - name: Store npm artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs/*
          retention-days: 2

