name: Frontend Build and Publish Library
on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use (defaults to 18)
        required: false
        type: string
        default: '18'
      npm-registry:
        description: The url for npm registry
        required: false
        type: string
        default: //nexus.rivertech.dev/repository/npm/
      npm-registry-publish:
          description: The address for npm registry publish
          required: false
          type: string
          default: //nexus.rivertech.dev/repository/odin-npm/
      npm-registry-scope:
        description: The name of the npm scope (defaults to @odin)
        required: false
        type: string
        default: '@odin'
      junit-report-path:
        description: The path to unit test report (defaults to ./junit/)
        required: false
        type: string
        default: ./junit/
      junit-report-name:
        description: The file name for unit test report (defaults to test-results.xml)
        required: false
        type: string
        default: test-results.xml
      aws-region:
        description: Which AWS region to use for publish storybook (defaults to eu-west-1)
        required: false
        type: string
        default: eu-west-1
      has-storybook:
        description: Whether storybook exists in project (defaults to false)
        required: false
        type: boolean
        default: false
      monoTemplate:
        description: Specify which template to use for mono repo e.g. 'lerna', 'node' (defaults to 'lerna')
        required: false
        type: string
        default: lerna
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      github-token:
        required: true

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and publish library
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          always-auth: true
          node-version: ${{ inputs.node-version }}

      - name: Print environment versions
        run: |
          NODE_V=$(node --version)
          NPM_V=$(npm -v)
          echo node version':' $NODE_V
          echo npm version':' $NPM_V

      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Get commit message and branch name
        id: git
        run: |
          EVENT=${{ github.event_name }}
          if [ $EVENT == "pull_request" ]; then
            BRANCH_NAME=${{github.head_ref}}
            echo "::set-output name=branch-name::${BRANCH_NAME}"
            echo ::set-output name=commit-message::$(git log --format=%B -n 1 HEAD^2)
          else
            echo "::set-output name=branch-name::${GITHUB_REF_NAME}"
            echo ::set-output name=commit-message::$(git log --format=%B -n 1 HEAD)
          fi

      - name: NPM TOKEN
        id: npm_token
        run: |
          NODE_AUTH_TOKEN=$(echo -n "${{ secrets.nexus-username }}:${{ secrets.nexus-password }}" | openssl base64 -e)
          echo "token=${NODE_AUTH_TOKEN}" >> "$GITHUB_OUTPUT"

      - name: Setup Environment
        run: |
          npm config set ${{inputs.npm-registry}}:_auth=${{ steps.npm_token.outputs.token }}
          npm config set ${{inputs.npm-registry-publish}}:_auth=${{ steps.npm_token.outputs.token }}
          npm config set registry=https:${{ inputs.npm-registry }}
          npm config set @odin:registry=https:${{ inputs.npm-registry-publish }}

      # todo: uncomment
      # - name: Install npm
      #   run: npm ci

      # - name: Build
      #   run: npm run build

      # - name: Test
      #   run: npm run test -- --browsers=ChromeHeadlessCI --no-watch --no-progress

      - name: Build storybook
        if: inputs.has-storybook
        run: npm run build:storybook

      - name: Check if branch is publishable
        id: check-branch
        env:
          BRANCH_NAME: ${{ steps.git.outputs.branch-name}}
        run: |
          echo "::notice ::Branch name: $BRANCH_NAME"

          if ! ([ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "vnext" ] || [[ "$BRANCH_NAME" =~ ^([0-9].*)\.x$ ]]); then
            echo "::set-output name=publishable::false"
            echo "::notice ::Non-publishable branch."
          else 
            echo "::set-output name=publishable::true"
          fi

      - name: Check if commit is publishable
        id: commit
        env:
          COMMIT_MESSAGE: ${{ steps.git.outputs.commit-message}}
        run: |
          echo "::notice ::Commit message: $COMMIT_MESSAGE"

          if [[ "$COMMIT_MESSAGE" =~ ^(style|test|docs) ]]; then
            echo "::set-output name=publishable::false"
            echo "::notice ::This update doesn't need to be published."
          else 
            echo "::set-output name=publishable::true"
          fi

      - name: Get package version
        id: versioning
        if: ${{ steps.commit.outputs.publishable == 'true' }}
        run: |
          # TAG=$(node -p "require('./lerna.json').version")
          # echo "::set-output name=version::${TAG}"
          echo "MONO TEMPLATE: ${{ inputs.monoTemplate }}"
          if [[ ${{ inputs.monoTemplate }} == "lerna" ]]; then
            echo "LERNA!"
            echo "VERSION_FILE=lerna" >> $GITHUB_ENV
          elif [[ ${{ inputs.monoTemplate }} == "node" ]]; then
            echo "NODE!"
            echo "VERSION_FILE=package" >> $GITHUB_ENV
          else
          echo "NOT HANDLED!"
          fi
          echo "VERSION FILE: $VERSION_FILE"
          PACKAGE_VERSION=$(node -p "require('./$VERSION_FILE.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: tag
        with: 
          tag: ${{ env.PACKAGE_VERSION }}
          # tag: ${{ steps.lerna.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Inform if tag exists
        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.exists == 'true' }}
        run: |
          echo "::error ::Tag already exists. Please make sure you bump version!"
          exit 1

      - name: Configure AWS credentials
        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish storybook
        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
        env:
          ECR_HOST: ${{ steps.login-ecr.outputs.registry }}
          BRANCH_NAME: ${{ steps.git.outputs.branch-name}}
        run: |
          TAG=$(node -p "require('./storybook/package.json').version")
          if [ "$BRANCH_NAME" = "develop" ]
          then
            TAG=$TAG-dev-$GITHUB_RUN_ID
          elif [[ "$BRANCH_NAME" =~ ^feature\/(.*)$ ]]
          then
            TAG=$TAG-demo-${BASH_REMATCH[1]}-$GITHUB_RUN_ID
          fi

          [[ $ECR_HOST =~ ^([0-9]*) ]] && REGISTRY=${BASH_REMATCH[1]}

          if aws ecr describe-images --repository-name=odin.ngx-storybook --registry-id $REGISTRY --image-ids=imageTag=$TAG > /dev/null 2>&1; then
            echo "::notice ::$TAG already exists on remote... skipping..."
            exit 0
          fi

          TAG=$TAG docker-compose build
          TAG=$TAG docker-compose push

      - name: Logout of Amazon ECR
        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

      - name: Deploy
        if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.commit.outputs.publishable == 'true' }}
        run: |
          echo "PKG VER: $PACKAGE_VERSION" # todo: remove
          # PACKAGE_VERSION=$(node -p "require('./lerna.json').version")

          echo "Tagging code base"
          git tag $PACKAGE_VERSION
          git push origin $PACKAGE_VERSION
          
          echo "Publishing ..."
          npm run publish:rel

      - name: Store tests artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ inputs.junit-report-name }}
          path: ${{ inputs.junit-report-path }}
          retention-days: 2

      - name: Store npm artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs/*
          retention-days: 2
