name: Frontend Build and Publish Apps
on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use (defaults to 14)
        required: false
        type: string
        default: '14'
      npm-registry-url:
        description: The url address for npm registry (defaults to https://www.myget.org/F/river-tech/npm/)
        required: false
        type: string
        default: https://www.myget.org/F/river-tech/npm/
      npm-registry-scope:
        description: The name of the npm scope (defaults to @odin)
        required: false
        type: string
        default: '@odin'
      aws-region:
        description: Which AWS region to use for publish storybook (defaults to eu-west-1)
        required: false
        type: string
        default: eu-west-1
      dotnet-version:
        description: dotnet version to use (defaults to 6.0.x)
        required: false
        type: string
        default: '6.0.x'
    secrets:
      npm-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      github-token:
        required: true
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      PUBLISH_PATH: obj/Docker/publish
      ODIN_CI_DEBUG_MODE: "true"
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          always-auth: true
          registry-url: ${{ inputs.npm-registry-url }}
          scope: ${{ inputs.npm-registry-scope }}
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Print environment versions
        run: |
          NODE_V=$(node --version)
          NPM_V=$(npm -v)
          echo node version':' $NODE_V
          echo npm version':' $NPM_V
          docker -v
          docker-compose -v
          DOTNET_CLI_V=$(dotnet --version)
          echo dotnet cli version':' $DOTNET_CLI_V
          git --version

      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Extract branch name
        id: branch
        run: |
          EVENT=${{ github.event_name }}
          if [ $EVENT == "pull_request" ]; then
            BRANCH_NAME=${{github.head_ref}}
            echo "::set-output name=name::${BRANCH_NAME}"
          else
            echo "::set-output name=name::${GITHUB_REF_NAME}"
          fi

      - name: Check if branch is publishable
        id: check-branch
        run: |
          BRANCH_NAME=${{steps.branch.outputs.name}}
          echo "::notice ::Branch name: $BRANCH_NAME"

          if ! ([ $BRANCH_NAME = "develop" ] || [ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "vnext" ] || [[ "$BRANCH_NAME" =~ ^(feature|hotfix)\/(.*)$ ]] || [[ "$BRANCH_NAME" =~ ^(([0-9]+|\.)+x)$ ]]); then
            echo "::set-output name=publishable::false"
            echo "::notice ::Non-publishable branch."
          else 
            echo "::set-output name=publishable::true"
          fi

      # - name: Install npm
      #   run: npm ci
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      # - name: Lint
      #   run: npm run lint

      # - name: Build
      #   run: npm run build:rel

      # - name: Install tools
      #   run: npm i -g @odin/infra.ci@0.1.22
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      # - name: Dotnet restore/publish
      #   run: |
      #       SOLUTION=$(node -p "require('./package.json').vsBuildSolution")
      #       dotnet restore $SOLUTION /p:Configuration=Release
      #       dotnet publish $SOLUTION -c Release -o ./$PUBLISH_PATH

      # - name: Set environment variables
      #   run: |
      #     BRANCH_NAME=${{steps.branch.outputs.name}}
      #     echo "::notice ::Branch name: $BRANCH_NAME"

      #     PACKAGE_VERSION=$(node -p "require('./package.json').version")
      #     echo "APP_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV
      #     echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      #     if [[ "$BRANCH_NAME" =~ ^feature\/(.*)$ ]]
      #     then
      #       echo "APP_VERSION=$PACKAGE_VERSION-demo-${BASH_REMATCH[1]}-$GITHUB_RUN_ID" >> $GITHUB_ENV
      #     elif [[ "$BRANCH_NAME" =~ ^hotfix\/(.*)$ ]]
      #     then
      #       echo "APP_VERSION=$PACKAGE_VERSION-hotfix-${BASH_REMATCH[1]}-$GITHUB_RUN_ID" >> $GITHUB_ENV
      #     else
      #       echo "APP_VERSION=$(ci get:app-version --packageVersion=$PACKAGE_VERSION --branch=$BRANCH_NAME --incrementalSuffix=$GITHUB_RUN_ID)" >> $GITHUB_ENV
      #     fi

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: tag
        with:
          tag: ${{ env.APP_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Inform if tag exists
        if: ${{ steps.tag.outputs.exists == 'true' }}
        run: echo "::notice ::Tag already exists."

      # - name: Configure AWS credentials
      #   if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.tag.outputs.exists == 'false' }}
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.aws-access-key-id }}
      #     aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
      #     aws-region: ${{ inputs.aws-region }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.tag.outputs.exists == 'false' }}
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Deploy
      #   if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.tag.outputs.exists == 'false' }}
      #   env:
      #     ECR_HOST: ${{ steps.login-ecr.outputs.registry }}
      #   run: |
      #     docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.ci.yml build
      #     docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.ci.yml push

      # - name: Logout of Amazon ECR
      #   if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.tag.outputs.exists == 'false' }}
      #   run: docker logout ${{ steps.login-ecr.outputs.registry }}

      # - name: Create Git tag for release
      #   if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.tag.outputs.exists == 'false' }}
      #   run: |
      #     git tag $APP_VERSION
      #     git push origin $APP_VERSION

      - name: Checkout develop
        uses: actions/checkout@v3
        if: ${{ steps.check-branch.outputs.publishable == 'true' }}
        with:
          ref: refs/heads/feature/test2
          fetch-depth: 0
          token: ${{ secrets.github-token }}

      - name: Downmerge master to develop
        if: ${{ steps.check-branch.outputs.publishable == 'true' }}
        run:  |
          BRANCH_NAME=${{steps.branch.outputs.name}}

          if [ "$BRANCH_NAME" != "feature/test" ]
          then
            echo "::notice ::Skipping downmerge. Branch is not master."
            exit 0
          fi

          git fetch
          git checkout feature/test2
          git config user.email "deploy-bot@riverigaming.com"
          git config user.name "rig-autobot"

          if git merge --no-commit --no-ff --no-edit origin/feature/test
          then
            if [ -z "$(git status --porcelain)" ]
            then
              echo "::notice ::Nothing to commit"
            else
              git commit --no-edit
              git push origin feature/test2
            fi
          else
            if git merge HEAD
            then
              echo "::notice ::"Nothing to merge"
            else
              echo "::warning ::"Failed to downmerge. Conflicts between master and develop."
              git merge --abort
            fi
          fi

      - name: Store npm artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs/*
          retention-days: 2
