on:
  workflow_call:
    # inputs:
    #   exec-project:
    #     description: The main executable project
    #     required: false
    #     type: string
    #     default: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: make fake files
        run: |
          mkdir -p {p1,p2,p3}/target
          a >> p1/target/project-exec.jar
          b >> p2/target/project-exec.jar
          c >> p3/target/project-exec.jar
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: projects
          path: "**/target/*-exec.jar"
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
        
  package:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/download-artifact@v4
        with:
          name: projects
      - name: Display structure of downloaded files
        run: ls -R
