on:
  workflow_call:
    inputs:
      projects:
        description: all project to build docker stuff u hekk
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: make fake files
        run: |
          mkdir -p {p1,p2,p3}/target
          echo a >> p1/target/project-exec.jar
          echo b >> p2/target/project-exec.jar
          echo c >> p3/target/project-exec.jar
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: projects
          path: "**/target/*-exec.jar"
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
        
  package:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        project: ${{ fromJSON(inputs.projects)}}
    steps: 
      - uses: actions/download-artifact@v4
        with:
          name: projects
      - name: Display structure of downloaded files
        run: ls -R  ${{ matrix.project }}
