name: Maven Deploy and Docker Package

on:
  workflow_call:
    inputs:
      exec-project:
        description: The main executable project
        required: false
        type: string
        default: '.'
      ecr-repository:
        description: Name of ECR repository for project
        required: true
        type: string
      java-version:
        description: JDK version (defaults to 8)
        required: false
        type: string
        default: '8'
      maven-command:
        description: The maven command to execute for main build
        required: false
        type: string
        default: 'mvn -B deploy -ntp'
      maven-extra-args:
        description: Additional maven arguments to be appended to command
        required: false
        type: string
      docker-platforms:
        description: "Comma seperated list of platforms to use when building the docker image"
        required: false
        type: string
        default: "linux/amd64,linux/arm64"
      docker_version_suffix:
        description: "Base Docker Image Tag"
        required: false
        type: string        
        default: "1.7.0"        
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      sonar-token:
        required: false
    outputs:
      project-version:
        value: ${{ jobs.build.outputs.project-version }}
      image-version:
        value: ${{ jobs.build.outputs.final-version }}
jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.versioning.outputs.project-version }}
      image-version: ${{ steps.versioning.outputs.final-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1 
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Setting up maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id": "river-nexus", "username": "${{ secrets.nexus-username }}", "password": "${{ secrets.nexus-password }}" },{ "id": "platform-snapshots", "username": "${{ secrets.nexus-username }}", "password": "${{ secrets.nexus-password }}" },{ "id": "platform-releases", "username": "${{ secrets.nexus-username }}", "password": "${{ secrets.nexus-password }}" }]'
          mirrors: '[{ "id": "river-nexus", "mirrorOf": "*", "url": "https://nexus.riverigaming.tech/repository/maven-public/" }]'
          repositories: '[{ "id": "river-nexus", "url": "https://nexus.riverigaming.tech/repository/platform-releases" }]'

      - name: Cache
        if: ${{ github.run_attempt == 1 }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/river
            !~/.m2/repository/com/bejig
          key: river-cache
          restore-keys: river-cache

      - name: Build with Maven
        run: ${{ inputs.maven-command }} ${{ inputs.maven-extra-args }}

      - name: Run SonarQube if enabled
        if: env.SONAR_TOKEN
        run: mvn -ntp sonar:sonar -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}

      - name: Get release version
        id: versioning
        run: |
          PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
          BRANCH=${{ github.ref_name }}
          if [ ${{github.run_attempt}} -eq 1 ]
          then
            BUILD_NUMBER=${{ github.run_number}}
          else
            BUILD_NUMBER=${{ github.run_number}}-${{github.run_attempt}}
          fi
          case $BRANCH in
            master)
              VERSION=$BRANCH-$PROJECT_VERSION
              ;;
            develop)
              VERSION=$(echo $BRANCH-$PROJECT_VERSION | sed "s/-SNAPSHOT/-$BUILD_NUMBER/")
              ;;
            *)
              VERSION=$BRANCH-$BUILD_NUMBER
              ;;
          esac
          RELEASE_TAG=$( echo $VERSION | sed "s/[^[:alnum:]#._-]/-/g" )
          echo "::notice::Setting ${{ inputs.ecr-repository }} version to: $RELEASE_TAG"
          echo "project-version=$PROJECT_VERSION" >> $GITHUB_OUTPUT
          echo "final-version=$RELEASE_TAG" >> $GITHUB_OUTPUT
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ########
      # beginning of common functionality to build multi-platform docker images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Setup Docker buildx
        id: buildx-setup
        uses: docker/setup-buildx-action@v2

      - name: Inspect builder
        shell: bash
        run: |
          echo "Name:      ${{ steps.buildx-setup.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx-setup.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx-setup.outputs.status }}"
          echo "Flags:     ${{ steps.buildx-setup.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx-setup.outputs.platforms }}"

      - name: Select Docker Image Tag
        id: select_docker
        run: |
          JAVA_VERSION=$(java -version 2>&1 | awk -F '\"' '/version/ {print $2}')
          JAVA_MAJOR_VERSION=$(echo $JAVA_VERSION | awk -F. '{if ($1==1) print $2; else print $1}')
          
          case $JAVA_MAJOR_VERSION in
              8)
                  DOCKER_IMAGE="corretto-jre8-${{ inputs.docker_version_suffix }}"
                  ;;
              11)
                  DOCKER_IMAGE="corretto-jre11-${{ inputs.docker_version_suffix }}"
                  ;;
              17)
                  DOCKER_IMAGE="corretto-jre17-${{ inputs.docker_version_suffix }}"
                  ;;
              21)
                  DOCKER_IMAGE="corretto-jre21-${{ inputs.docker_version_suffix }}"
                  ;;
              *)
                  echo "Unsupported Java version: $JAVA_VERSION"
                  exit 1
                  ;;
          esac
          echo "SELECTED_DOCKER_IMAGE=$DOCKER_IMAGE" >> "$GITHUB_ENV"
          echo "BASE_IMAGE_VERSION=${{ inputs.docker_version_suffix }}" >> "$GITHUB_ENV"


      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.versioning.outputs.final-version }}
          EXEC_PROJECT: ${{ inputs.exec-project }}
          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
          SELECTED_DOCKER_IMAGE: ${{ env.SELECTED_DOCKER_IMAGE }}
        run: |
          REPO=$(git config --get remote.origin.url)
          DATE=$(date --utc +%FT%TZ)
          docker buildx build \
          --build-arg JAR_FILE=$EXEC_PROJECT/target/*-exec.jar \
          --build-arg GIT_HASH=${{ github.sha }} \
          --build-arg DATE="$DATE" \
          --build-arg GIT_REPO=$REPO \
          --build-arg GIT_REF=${{ github.ref }} \
          --build-arg VERSION=${{ env.VERSION }} \
          --build-arg BASE_IMAGE_TAG=$SELECTED_DOCKER_IMAGE \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --platform ${{ inputs.docker-platforms }} \
          --progress plain --push .

          echo "::notice::Pushed image $ECR_REPOSITORY: $IMAGE_TAG"

      # end of common multi-platform build functionality
      #########

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
