name: Node library build/publish
on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use (defaults to 18)
        required: false
        type: string
        default: '18'
      npm-registry:
        description: The url for npm registry
        required: false
        type: string
        default: //nexus.rivertech.dev/repository/npm/
      npm-registry-publish:
          description: The address for npm registry publish
          required: false
          type: string
          default: //nexus.rivertech.dev/repository/odin-npm/
      npm-registry-scope:
        description: The name of the npm scope (defaults to @odin)
        required: false
        type: string
        default: '@odin'
      junit-report-path:
        description: The path to unit test report (defaults to ./junit/)
        required: false
        type: string
        default: ./junit/
      junit-report-name:
        description: The file name for unit test report (defaults to test-results.xml)
        required: false
        type: string
        default: test-results.xml
      aws-region:
        description: Which AWS region to use for publish storybook (defaults to eu-west-1)
        required: false
        type: string
        default: eu-west-1
      has-storybook:
        description: Whether storybook exists in project (defaults to false)
        required: false
        type: boolean
        default: false
      mono-template:
        description: Specify which template to use for mono repo e.g. 'lerna', 'node' (defaults to 'lerna')
        required: false
        type: string
        default: lerna
      publish-command:
        description: "Command to run to publish packages (defaults to: `npm run release` NOTE: NOT `npm publish`)"
        type: string
        default: npm run release
        required: false
      skip-lint:
        description: "Determines whether to skip linting (defaults to false)"
        type: boolean
        default: false
        required: false
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      github-token:
        required: true

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: build & publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM TOKEN
        id: npm_token
        run: |
          NODE_AUTH_TOKEN=$(echo -n "${{ secrets.nexus-username }}:${{ secrets.nexus-password }}" | openssl base64 -e)
          echo "token=${NODE_AUTH_TOKEN}" >> "$GITHUB_OUTPUT"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Setup Environment
        run: |
          npm config set ${{inputs.npm-registry}}:_auth=${{ steps.npm_token.outputs.token }}
          npm config set ${{inputs.npm-registry-publish}}:_auth=${{ steps.npm_token.outputs.token }}
          npm config set registry=https:${{ inputs.npm-registry }}
          npm config set @odin:registry=https:${{ inputs.npm-registry-publish }}

      - name: Print environment versions
        run: |
          NODE_V=$(node --version)
          NPM_V=$(npm -v)
          echo node version':' $NODE_V
          echo npm version':' $NPM_V

      - name: Get commit message and branch name
        id: git
        run: |
          EVENT=${{ github.event_name }}
          if [ $EVENT == "pull_request" ]; then
            BRANCH_NAME=${{github.head_ref}}
            # COMMIT_MSG=$(git log --format=%B -n 1 HEAD^1)
            COMMIT_MSG=$(git log -n 2 --format=%B HEAD^1)
          else
            BRANCH_NAME=$GITHUB_REF_NAME
            # COMMIT_MSG=$(git log --format=%B -n 1 HEAD)
            COMMIT_MSG=$(git log -1 --format=%B)
          fi
          echo "::notice ::Branch name: $BRANCH_NAME :: Commit message: $COMMIT_MSG"
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "commit-message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: npm ci

      - name: Lint
        if: ${{!inputs.skip-lint}}
        run: npm run lint --if-present

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci --if-present

      - name: Build storybook
        if: inputs.has-storybook
        run: npm run build:storybook

      - name: Check if branch is publishable
        id: check-branch
        env:
          BRANCH_NAME: ${{ steps.git.outputs.branch-name}}
        run: |
          echo "::notice ::Branch name: $BRANCH_NAME"

          if ! ([ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "vnext" ] || [[ "$BRANCH_NAME" =~ ^([0-9].*)\.x$ ]]); then
            PUBLISHABLE=false
            echo "::notice ::Non-publishable branch."
          else 
            PUBLISHABLE=true
          fi
          echo "publishable=$PUBLISHABLE" >> $GITHUB_OUTPUT

      - name: Check if commit is publishable
        id: commit
        env:
          COMMIT_MESSAGE: ${{ steps.git.outputs.commit-message}}
        run: |
          echo "::notice ::Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" =~ ^(style|test|docs) ]]; then
            PUBLISHABLE=false
            echo "::notice ::Commit doesn't need to be published."
          else
            PUBLISHABLE=true
          fi
          echo "publishable=$PUBLISHABLE" >> $GITHUB_OUTPUT

      - name: Set publishable envs
        run: |
          PUBLISHABLE=${{steps.check-branch.outputs.publishable == 'true' && steps.commit.outputs.publishable == 'true'}}
          STORYBOOK_PUBLISHABLE=${{inputs.has-storybook == true && steps.commit.outputs.publishable == 'true'}}
          echo "PUBLISHABLE=$PUBLISHABLE" >> $GITHUB_ENV
          echo "STORYBOOK_PUBLISHABLE=$STORYBOOK_PUBLISHABLE" >> $GITHUB_ENV

      - name: Get package version
        id: versioning
        if: ${{ steps.commit.outputs.publishable == 'true' }}
        run: |
          if [[ ${{ inputs.mono-template }} == "lerna" ]]; then
            VERSION_FILE=lerna
          elif [[ ${{ inputs.mono-template }} == "node" ]]; then
            VERSION_FILE=package
          else
            echo "::error ::Mono template '${{ inputs.mono-template }}' not handled!"
            exit 1
          fi
          PACKAGE_VERSION=$(node -p "require('./$VERSION_FILE.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.2.0
        id: tag
        with:
          tag: ${{ env.PACKAGE_VERSION }}

      - name: Error if tag exists
        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.exists == 'true' }}
        run: |
          echo "::error ::Tag already exists. Please make sure you bump version!"
          exit 1

      - name: Configure AWS credentials
        if: ${{ env.STORYBOOK_PUBLISHABLE == 'true' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        if: ${{ env.STORYBOOK_PUBLISHABLE == 'true' }}
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish storybook
        if: ${{ env.STORYBOOK_PUBLISHABLE == 'true' }}
        env:
          ECR_HOST: ${{ steps.login-ecr.outputs.registry }}
          BRANCH_NAME: ${{ steps.git.outputs.branch-name}}
        run: |
          TAG=$PACKAGE_VERSION

          # todo: try and replace by using the name from the package.json instead (but was not able to change it e.g. npm i fails)
          # STORYBOOK_NAME=$(node -p "require('./storybook/package.json').name")
          STORYBOOK_NAME=$(node -p "require('./storybook/package.json').dockerName")
          echo "Storybook Docker Repo Name: $STORYBOOK_NAME"

          if [ "$BRANCH_NAME" = "develop" ]
          then
            TAG=$TAG-dev-$GITHUB_RUN_ID
          elif [[ "$BRANCH_NAME" =~ ^feature\/(.*)$ ]]
          then
            TAG=$TAG-demo-${BASH_REMATCH[1]}-$GITHUB_RUN_ID
          fi

          [[ $ECR_HOST =~ ^([0-9]*) ]] && REGISTRY=${BASH_REMATCH[1]}

          if aws ecr describe-images --repository-name=$STORYBOOK_NAME --registry-id $REGISTRY --image-ids=imageTag=$TAG > /dev/null 2>&1; then
            echo "::notice ::$TAG already exists on remote... skipping..."
            exit 0
          fi

          TAG=$TAG docker-compose build
          TAG=$TAG docker-compose push

      - name: Logout of Amazon ECR
        if: ${{ env.STORYBOOK_PUBLISHABLE == 'true' }}
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

      - name: Publish
        if: ${{ env.PUBLISHABLE == 'true' }}
        run: |
          echo "Publishing ..."
          ${{ inputs.publish-command }}

          echo "Tagging code base"
          git tag $PACKAGE_VERSION
          git push origin $PACKAGE_VERSION

      - name: Store tests artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ inputs.junit-report-name }}
          path: ${{ inputs.junit-report-path }}
          retention-days: 2

      - name: Store npm artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs/*
          retention-days: 2
