name: Config Checks

on:
  workflow_call:

jobs:
  checks:
    name: JSON Lint and Check Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: npm run lint
      - name: Get version
        id: get-version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "package-version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.7.0
        id: tag
        with:
          tag: ${{ steps.get-version.outputs.package-version }}

      - uses: mshick/add-pr-comment@v2
        name: Add PR comment
        if: ${{ steps.tag.outputs.exists == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Tag corresponding to package version [**${{ steps.get-version.outputs.package-version }}**] already exists.
            _Bumping version in package.json_.
          allow-repeats: true
      - name: Bump version
        id: version-bump
        if: ${{ steps.tag.outputs.exists == 'true' }}
        run: |
          npm version patch --no-git-tag-version
          NEW_PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if git ls-remote --exit-code origin refs/tags/$NEW_PACKAGE_VERSION; then
              echo "::error::Attempted to bump version to [$NEW_PACKAGE_VERSION] but tag already exists"
              exit 1
          else
              COMMENT="Bumped version from [${{ steps.get-version.outputs.package-version }}] to [$NEW_PACKAGE_VERSION]"
              echo "::notice::$COMMENT"
              echo "new-version=$NEW_PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
              echo "git-comment=$COMMENT" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit bumped version
        if: ${{ steps.tag.outputs.exists == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@river.tech"
          git add package.json
          git commit -m "chore(version): bump version to ${{ steps.version-bump.outputs.new-version }}"
          git push
