name: Config Checks

on:
  workflow_call:

jobs:
  checks:    
    name: JSON Lint and Check Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Prepare linter
        run: |          
          npm install -g eslint eslint-plugin-jsonc          
          echo '{ "extends": ["plugin:jsonc/recommended-with-jsonc"] }' > .eslintrc.json
      - name: Lint JSON files
        run: eslint config/** --ext .json -f checkstyle -o checkstyle-result.xml --resolve-plugins-relative-to=$(npm root -g)
      - name: Output Report
        if: ${{ failure() }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: checkstyle-result.xml
      - name: Get version
        id: get-version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=package-version::$PACKAGE_VERSION"
      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: tag
        with:
          tag: ${{ steps.get-version.outputs.package-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mshick/add-pr-comment@v1
        name: Add PR comment
        if: ${{ steps.tag.outputs.exists == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Tag corresponding to package version [**${{ steps.get-version.outputs.package-version }}**] already exists.
            _Bumping version in package.json_.
          allow-repeats: true
      - name: Bump version
        id: version-bump
        if: ${{ steps.tag.outputs.exists == 'true' }}
        run: |
          npm install -g bump
          bump
          NEW_PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ $(git ls-remote origin refs/tags/$NEW_PACKAGE_VERSION) ]; then
              echo "::error::Attempted to bump version to [$NEW_PACKAGE_VERSION] but tag already exists"
              exit 1
          else
              COMMENT="Bumped version from [${{ steps.get-version.outputs.package-version }}] to [$NEW_PACKAGE_VERSION]"                    
              echo "::notice::$COMMENT"
              echo "::set-output name=git-comment::$COMMENT"
          fi          
      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        if: ${{ steps.tag.outputs.exists == 'true' }}
        with:
          file_pattern: package.json
          commit_message: ${{ steps.version-bump.outputs.git-comment }} 
